#pragma checksum "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "782DC6DB7B3DE5D024BF0DFFEE9CDCC427729863"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.Xaml.Behaviors;
using Microsoft.Xaml.Behaviors.Core;
using Microsoft.Xaml.Behaviors.Input;
using Microsoft.Xaml.Behaviors.Layout;
using Microsoft.Xaml.Behaviors.Media;
using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.UI.Xaml.Charts;
using Syncfusion.UI.Xaml.NavigationDrawer;
using Syncfusion.UI.Xaml.TreeView;
using Syncfusion.UI.Xaml.TreeView.Engine;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Layout;
using Syncfusion.Windows.Controls.Navigation;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.PropertyGrid;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.demoscommon.wpf;
using syncfusion.navigationdemos.wpf;


namespace syncfusion.navigationdemos.wpf {
    
    
    /// <summary>
    /// RadialMenuDemosView
    /// </summary>
    public partial class RadialMenuDemosView : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 32 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RichTextBox text;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenu selectionmenu;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform transform1;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem BoldItem;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem bold;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem italic;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem bullet;
        
        #line default
        #line hidden
        
        
        #line 172 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Bullet;
        
        #line default
        #line hidden
        
        
        #line 189 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem subscript;
        
        #line default
        #line hidden
        
        
        #line 216 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem superscript;
        
        #line default
        #line hidden
        
        
        #line 243 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem strike;
        
        #line default
        #line hidden
        
        
        #line 252 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Strikethrough;
        
        #line default
        #line hidden
        
        
        #line 270 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem underline;
        
        #line default
        #line hidden
        
        
        #line 279 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Underline;
        
        #line default
        #line hidden
        
        
        #line 301 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem Outer_Copy;
        
        #line default
        #line hidden
        
        
        #line 310 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Copy;
        
        #line default
        #line hidden
        
        
        #line 327 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem Cut;
        
        #line default
        #line hidden
        
        
        #line 336 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path cut;
        
        #line default
        #line hidden
        
        
        #line 355 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem Inner_Copy;
        
        #line default
        #line hidden
        
        
        #line 382 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem Paste;
        
        #line default
        #line hidden
        
        
        #line 392 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path paste;
        
        #line default
        #line hidden
        
        
        #line 425 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem Main_undo;
        
        #line default
        #line hidden
        
        
        #line 434 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path undo;
        
        #line default
        #line hidden
        
        
        #line 443 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock Undotext1;
        
        #line default
        #line hidden
        
        
        #line 463 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem Inner_Undo;
        
        #line default
        #line hidden
        
        
        #line 478 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock undotext2;
        
        #line default
        #line hidden
        
        
        #line 487 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem Inner_Redo;
        
        #line default
        #line hidden
        
        
        #line 496 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Redo;
        
        #line default
        #line hidden
        
        
        #line 549 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialSlider FontsizeSlider;
        
        #line default
        #line hidden
        
        
        #line 571 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem palette;
        
        #line default
        #line hidden
        
        
        #line 598 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem radialcoloritem;
        
        #line default
        #line hidden
        
        
        #line 609 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Orange;
        
        #line default
        #line hidden
        
        
        #line 615 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Orange1;
        
        #line default
        #line hidden
        
        
        #line 621 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Orange2;
        
        #line default
        #line hidden
        
        
        #line 627 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Gold;
        
        #line default
        #line hidden
        
        
        #line 633 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem LightYellow;
        
        #line default
        #line hidden
        
        
        #line 639 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem LightYellow1;
        
        #line default
        #line hidden
        
        
        #line 645 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Yellow;
        
        #line default
        #line hidden
        
        
        #line 651 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Brown;
        
        #line default
        #line hidden
        
        
        #line 659 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkRed;
        
        #line default
        #line hidden
        
        
        #line 665 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Purple;
        
        #line default
        #line hidden
        
        
        #line 671 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Plum;
        
        #line default
        #line hidden
        
        
        #line 677 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkRed1;
        
        #line default
        #line hidden
        
        
        #line 683 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkRed2;
        
        #line default
        #line hidden
        
        
        #line 689 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Red1;
        
        #line default
        #line hidden
        
        
        #line 695 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Rose;
        
        #line default
        #line hidden
        
        
        #line 701 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Rose1;
        
        #line default
        #line hidden
        
        
        #line 707 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Pink;
        
        #line default
        #line hidden
        
        
        #line 715 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkGreen;
        
        #line default
        #line hidden
        
        
        #line 721 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Green;
        
        #line default
        #line hidden
        
        
        #line 727 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkGreen1;
        
        #line default
        #line hidden
        
        
        #line 733 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkGreen2;
        
        #line default
        #line hidden
        
        
        #line 739 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkGreen3;
        
        #line default
        #line hidden
        
        
        #line 745 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkGreen4;
        
        #line default
        #line hidden
        
        
        #line 751 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkGreen5;
        
        #line default
        #line hidden
        
        
        #line 757 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Lime;
        
        #line default
        #line hidden
        
        
        #line 763 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem LightGreen;
        
        #line default
        #line hidden
        
        
        #line 771 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkBlue;
        
        #line default
        #line hidden
        
        
        #line 777 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Turquoise;
        
        #line default
        #line hidden
        
        
        #line 783 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Aqua;
        
        #line default
        #line hidden
        
        
        #line 789 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem SkyBlue;
        
        #line default
        #line hidden
        
        
        #line 795 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Purple1;
        
        #line default
        #line hidden
        
        
        #line 801 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkPurple;
        
        #line default
        #line hidden
        
        
        #line 807 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkBlue1;
        
        #line default
        #line hidden
        
        
        #line 813 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Blue;
        
        #line default
        #line hidden
        
        
        #line 819 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem DarkBlue2;
        
        #line default
        #line hidden
        
        
        #line 827 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black;
        
        #line default
        #line hidden
        
        
        #line 833 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black1;
        
        #line default
        #line hidden
        
        
        #line 839 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black2;
        
        #line default
        #line hidden
        
        
        #line 845 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black3;
        
        #line default
        #line hidden
        
        
        #line 851 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black4;
        
        #line default
        #line hidden
        
        
        #line 857 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black5;
        
        #line default
        #line hidden
        
        
        #line 863 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black6;
        
        #line default
        #line hidden
        
        
        #line 869 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black7;
        
        #line default
        #line hidden
        
        
        #line 875 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialColorItem Black8;
        
        #line default
        #line hidden
        
        
        #line 887 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenu defaultmenu;
        
        #line default
        #line hidden
        
        
        #line 903 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Media.TranslateTransform transform2;
        
        #line default
        #line hidden
        
        
        #line 908 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path defaulticon;
        
        #line default
        #line hidden
        
        
        #line 922 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path camera;
        
        #line default
        #line hidden
        
        
        #line 939 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem defaultmenu_paste;
        
        #line default
        #line hidden
        
        
        #line 969 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem defaultmenu_Redo;
        
        #line default
        #line hidden
        
        
        #line 994 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem defaultmenu_Undo;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.4.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.navigationdemos.wpf;component/radialmenu/view/radialmenudemo.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\RadialMenu\View\RadialMenuDemo.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.4.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.text = ((System.Windows.Controls.RichTextBox)(target));
            return;
            case 2:
            this.selectionmenu = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenu)(target));
            return;
            case 3:
            this.transform1 = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 4:
            this.BoldItem = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 5:
            this.bold = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 6:
            this.italic = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 7:
            this.bullet = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 8:
            this.Bullet = ((System.Windows.Shapes.Path)(target));
            return;
            case 9:
            this.subscript = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 10:
            this.superscript = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 11:
            this.strike = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 12:
            this.Strikethrough = ((System.Windows.Shapes.Path)(target));
            return;
            case 13:
            this.underline = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 14:
            this.Underline = ((System.Windows.Shapes.Path)(target));
            return;
            case 15:
            this.Outer_Copy = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 16:
            this.Copy = ((System.Windows.Shapes.Path)(target));
            return;
            case 17:
            this.Cut = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 18:
            this.cut = ((System.Windows.Shapes.Path)(target));
            return;
            case 19:
            this.Inner_Copy = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 20:
            this.Paste = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 21:
            this.paste = ((System.Windows.Shapes.Path)(target));
            return;
            case 22:
            this.Main_undo = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 23:
            this.undo = ((System.Windows.Shapes.Path)(target));
            return;
            case 24:
            this.Undotext1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.Inner_Undo = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 26:
            this.undotext2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 27:
            this.Inner_Redo = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 28:
            this.Redo = ((System.Windows.Shapes.Path)(target));
            return;
            case 29:
            this.FontsizeSlider = ((Syncfusion.Windows.Controls.Navigation.SfRadialSlider)(target));
            return;
            case 30:
            this.palette = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 31:
            this.radialcoloritem = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 32:
            this.Orange = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 33:
            this.Orange1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 34:
            this.Orange2 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 35:
            this.Gold = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 36:
            this.LightYellow = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 37:
            this.LightYellow1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 38:
            this.Yellow = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 39:
            this.Brown = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 40:
            this.DarkRed = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 41:
            this.Purple = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 42:
            this.Plum = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 43:
            this.DarkRed1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 44:
            this.DarkRed2 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 45:
            this.Red1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 46:
            this.Rose = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 47:
            this.Rose1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 48:
            this.Pink = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 49:
            this.DarkGreen = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 50:
            this.Green = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 51:
            this.DarkGreen1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 52:
            this.DarkGreen2 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 53:
            this.DarkGreen3 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 54:
            this.DarkGreen4 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 55:
            this.DarkGreen5 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 56:
            this.Lime = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 57:
            this.LightGreen = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 58:
            this.DarkBlue = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 59:
            this.Turquoise = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 60:
            this.Aqua = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 61:
            this.SkyBlue = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 62:
            this.Purple1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 63:
            this.DarkPurple = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 64:
            this.DarkBlue1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 65:
            this.Blue = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 66:
            this.DarkBlue2 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 67:
            this.Black = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 68:
            this.Black1 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 69:
            this.Black2 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 70:
            this.Black3 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 71:
            this.Black4 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 72:
            this.Black5 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 73:
            this.Black6 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 74:
            this.Black7 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 75:
            this.Black8 = ((Syncfusion.Windows.Controls.Navigation.SfRadialColorItem)(target));
            return;
            case 76:
            this.defaultmenu = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenu)(target));
            return;
            case 77:
            this.transform2 = ((System.Windows.Media.TranslateTransform)(target));
            return;
            case 78:
            this.defaulticon = ((System.Windows.Shapes.Path)(target));
            return;
            case 79:
            this.camera = ((System.Windows.Shapes.Path)(target));
            return;
            case 80:
            this.defaultmenu_paste = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 81:
            this.defaultmenu_Redo = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            case 82:
            this.defaultmenu_Undo = ((Syncfusion.Windows.Controls.Navigation.SfRadialMenuItem)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

