#pragma checksum "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B4DBA9E9EC6C05AB8E9CD90F9320F4BEC20F81F8"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Syncfusion;
using Syncfusion.SfSkinManager;
using Syncfusion.UI.Xaml.Charts;
using Syncfusion.UI.Xaml.Controls.DataPager;
using Syncfusion.UI.Xaml.Grid;
using Syncfusion.UI.Xaml.Grid.Converter;
using Syncfusion.UI.Xaml.Grid.RowFilter;
using Syncfusion.UI.Xaml.ProgressBar;
using Syncfusion.UI.Xaml.TreeGrid;
using Syncfusion.UI.Xaml.TreeGrid.Filtering;
using Syncfusion.Windows;
using Syncfusion.Windows.Controls.Input;
using Syncfusion.Windows.Controls.Notification;
using Syncfusion.Windows.Shared;
using Syncfusion.Windows.Tools.Controls;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using syncfusion.datagriddemos.wpf;
using syncfusion.demoscommon.wpf;


namespace syncfusion.datagriddemos.wpf {
    
    
    /// <summary>
    /// ExcelLikeFilteringDemo
    /// </summary>
    public partial class ExcelLikeFilteringDemo : syncfusion.demoscommon.wpf.DemoControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 26 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock1;
        
        #line default
        #line hidden
        
        
        #line 31 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbAllowFilters;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock2;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock3;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbAllowFilterOrderID;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbImmediateUpdateColumnFilterOrderID;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbAllowBlankFiltersOrderID;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock4;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbAllowFilterProductName;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbImmediateUpdateColumnFilterProductName;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbAllowBlankFiltersProductName;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock5;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox FilterModeforProductName;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock6;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbAllowFilterShippedDate;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbImmediateUpdateColumnFilterShippedDate;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ckbAllowBlankFiltersShippedDate;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock textBlock7;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox FilterModeforShippedDate;
        
        #line default
        #line hidden
        
        
        #line 152 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Syncfusion.UI.Xaml.Grid.SfDataGrid syncgrid;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.4.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/syncfusion.datagriddemos.wpf;component/views/filtering/excellikefilteringdemo.xa" +
                    "ml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\Views\Filtering\ExcelLikeFilteringDemo.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "6.0.4.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.textBlock1 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.ckbAllowFilters = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 3:
            this.textBlock2 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.textBlock3 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.ckbAllowFilterOrderID = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 6:
            this.ckbImmediateUpdateColumnFilterOrderID = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 7:
            this.ckbAllowBlankFiltersOrderID = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 8:
            this.textBlock4 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.ckbAllowFilterProductName = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 10:
            this.ckbImmediateUpdateColumnFilterProductName = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            this.ckbAllowBlankFiltersProductName = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 12:
            this.textBlock5 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.FilterModeforProductName = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.textBlock6 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.ckbAllowFilterShippedDate = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 16:
            this.ckbImmediateUpdateColumnFilterShippedDate = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 17:
            this.ckbAllowBlankFiltersShippedDate = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 18:
            this.textBlock7 = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.FilterModeforShippedDate = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 20:
            this.syncgrid = ((Syncfusion.UI.Xaml.Grid.SfDataGrid)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

